version: "3.7"
services:
  home.user-management-service.server:
    image: nginx:alpine
    container_name: home.user-management-service.server
    working_dir: /app
    volumes:
      - ./:/app
      - ./.dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=user-management-service.loc
    networks:
      - default
      - reverse-proxy

  home.user-management-service.fpm:
    image: ruslandev89/php74-fpm-bitrix
    container_name: home.user-management-service.fpm
    working_dir: /app
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./:/app
      - ./.dev/php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.dev/php/php.ini:/etc/php/7.4/cli/php.ini
    networks:
      - default
      - mysql
      - memcached

networks:
  default:
    name: home.user-management-service
  mysql:
    external: true
  memcached:
    external: true
  reverse-proxy:
    external: true
